In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arrtwo=np.array([[2.3,4.5],[1,3]])
print(arrtwo)

[[2.3 4.5]
 [1.  3. ]]


In [5]:
arr.ndim

1

In [6]:
arrtwo.ndim

2

In [8]:
arrtwo.shape

(2, 2)

In [10]:
arr.dtype

dtype('int64')

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.random.rand(4,4)

array([[0.30827105, 0.96886083, 0.26307392, 0.25620817],
       [0.41575526, 0.29294198, 0.9464583 , 0.57693981],
       [0.55388655, 0.82874432, 0.65716405, 0.96874054],
       [0.71479233, 0.92594002, 0.30824191, 0.05002775]])

In [14]:
np.random.randint(7,size=(3,3))

array([[2, 2, 2],
       [0, 3, 0],
       [5, 4, 6]], dtype=int32)

In [15]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


Linear Algebra Stuffs

In [20]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [21]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [23]:
stat=np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stat)

np.int64(1)

In [25]:
np.max(stat)

np.int64(6)

Load from file

In [27]:
np.genfromtxt('data.txt',delimiter=',',dtype='int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])